use serde_json::{Map, Value};
use std::collections::BTreeSet;
use std::time::{SystemTime, UNIX_EPOCH};

/// Per-boot salt used to hash redacted values without making hashes stable
/// across reboots.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BootSalt([u8; 32]);

impl BootSalt {
    /// Generate a boot-local salt from process-local runtime entropy.
    ///
    /// This does not create authority material; it only prevents trace hashes
    /// from becoming stable plaintext surrogates across boots.
    pub fn generate() -> Self {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let pid = std::process::id();
        let seed = format!("acos-observability:{now}:{pid}:{:p}", &now);
        Self(*blake3::hash(seed.as_bytes()).as_bytes())
    }

    #[cfg(test)]
    fn fixed_for_tests() -> Self {
        Self([0xA5; 32])
    }

    fn keyed_hash(&self, bytes: &[u8]) -> String {
        let digest = blake3::keyed_hash(&self.0, bytes);
        digest.to_hex().to_string()
    }
}

/// Whitelist-only JSON redactor for observation traces.
#[derive(Clone, Debug)]
pub struct Redactor {
    salt: BootSalt,
    allowed_fields: BTreeSet<String>,
}

impl Redactor {
    pub fn new<I, S>(salt: BootSalt, allowed_fields: I) -> Self
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        Self {
            salt,
            allowed_fields: allowed_fields.into_iter().map(Into::into).collect(),
        }
    }

    /// Redact a JSON params object by keeping only explicitly whitelisted
    /// top-level fields in plaintext. Every other field is replaced by a
    /// deterministic hash scoped to this boot salt.
    pub fn redact_params(&self, params: &Value) -> Value {
        match params {
            Value::Object(map) => Value::Object(self.redact_object(map)),
            other => self.hash_value(other),
        }
    }

    fn redact_object(&self, map: &Map<String, Value>) -> Map<String, Value> {
        map.iter()
            .map(|(key, value)| {
                if self.allowed_fields.contains(key) {
                    (key.clone(), value.clone())
                } else {
                    (key.clone(), self.hash_value(value))
                }
            })
            .collect()
    }

    fn hash_value(&self, value: &Value) -> Value {
        let bytes = serde_json::to_vec(value).unwrap_or_else(|_| b"<unserializable>".to_vec());
        Value::String(format!("redacted:blake3:{}", self.salt.keyed_hash(&bytes)))
    }
}

/// Convenience API for trace ingress: redact all non-whitelisted params using
/// a boot salt generated by `mcpd` at startup.
pub fn redact_params<I, S>(params: &Value, allowed_fields: I, salt: &BootSalt) -> Value
where
    I: IntoIterator<Item = S>,
    S: Into<String>,
{
    Redactor::new(salt.clone(), allowed_fields).redact_params(params)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn trace_redacts_sensitive_params() {
        let params = json!({
            "path": "/tmp/status.txt",
            "password": "correct horse battery staple",
            "nested": {"token": "abc123"}
        });
        let redacted = Redactor::new(BootSalt::fixed_for_tests(), ["path"]).redact_params(&params);
        let rendered = redacted.to_string();

        assert_eq!(redacted["path"], json!("/tmp/status.txt"));
        assert!(rendered.contains("redacted:blake3:"));
        assert!(!rendered.contains("correct horse battery staple"));
        assert!(!rendered.contains("abc123"));
    }

    #[test]
    fn non_object_params_are_hashed() {
        let redacted = redact_params(
            &json!("secret prompt"),
            ["method"],
            &BootSalt::fixed_for_tests(),
        );
        let rendered = redacted.to_string();

        assert!(rendered.contains("redacted:blake3:"));
        assert!(!rendered.contains("secret prompt"));
    }

    #[test]
    fn boot_salt_changes_hashes() {
        let value = json!({"password": "same"});
        let left = Redactor::new(BootSalt([1; 32]), [] as [&str; 0]).redact_params(&value);
        let right = Redactor::new(BootSalt([2; 32]), [] as [&str; 0]).redact_params(&value);

        assert_ne!(left, right);
    }
}
